spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/sns"
    username: root
    password: mallang
  jpa:
    hibernate.ddl-auto: create # create option : table trop -> new create
    show-sql: true
  jmx:
    enabled: false